vpc_range = "172.20.2.0/24"
vpc_name = "project2"
subdomain = "test2"
FireWall_Name_Web = "${var.subdomain}-web_fw"
FireWall_Name_DB = "${var.subdomain}-db_fw"
Bastion_firewall_name = "${var.subdomain}-bastion_fw"