- name: Generate SSH key pair and add to authorized_keys
  hosts: localhost
  tasks:
    - name: Generate SSH key pair if it doesn't exist
      openssh_keypair:
        path: ~/.ssh/id_rsa
        type: rsa
        size: 4096
        state: present
