- name: Add hosts to known_hosts
  hosts: localhost
  gather_facts: no
  become: yes

  tasks:
    - name: Read IP addresses from inventory file
      ansible.builtin.slurp:
        src: inventory.txt
      register: inventory_file_content

    - name: Add hosts to known_hosts
      ansible.builtin.shell: |
        while IFS= read -r ip; do
          ssh-keyscan -H $ip >> ~/.ssh/known_hosts
        done <<< "{{ inventory_file_content.content | b64decode }}"
      ignore_errors: yes
