---
- name: Generate SSH key pair
  hosts: localhost
  tasks:
    - name: Generate SSH key pair if it doesn't exist
      shell:
        cmd: |
          ssh-keygen -t rsa -b 4096 -C "your_email@example.com" -N "" -f ~/.ssh/id_rsa
        creates: ~/.ssh/id_rsa

    - name: Retrieve public key
      command:
        cmd: cat ~/.ssh/id_rsa.pub
      register: public_key_output
      changed_when: false

    - name: Add public key to authorized_keys on web_servers
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ public_key_output.stdout }}"
      delegate_to: bastion

    - name: Add public key to authorized_keys on db_servers
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ public_key_output.stdout }}"
      delegate_to: bastion
