---
- name: Configure SSH access from bastion to web_servers and db_servers
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Generate SSH key pair
      ansible.posix.openssh_keypair:
        path: ~/.ssh/id_rsa
        type: rsa
        size: 4096

    - name: Retrieve public key
      ansible.builtin.slurp:
        src: ~/.ssh/id_rsa.pub
      register: public_key

    - name: Add public key to authorized_keys on web_servers
      ansible.builtin.copy:
        content: "{{ public_key.content }}"
        dest: "/root/.ssh/authorized_keys"
        mode: "0600"
      delegate_to: "{{ item }}"
      with_items: "{{ groups['web_servers'] }}"

    - name: Add public key to authorized_keys on db_servers
      ansible.builtin.copy:
        content: "{{ public_key.content }}"
        dest: "/root/.ssh/authorized_keys"
        mode: "0600"
      delegate_to: "{{ item }}"
      with_items: "{{ groups['db_servers'] }}"
