---
- name: Install Grafana and configure Prometheus datasource
  hosts: localhost
  become: true
  vars:
    grafana_version: "10.4.4"
    prometheus_url: "http://localhost:9090"
    download_dir: "/tmp"
  tasks:
    - name: Ensure apt-transport-https and other dependencies are installed
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
        state: present
        update_cache: yes

    - name: Create directory for Grafana keyring
      file:
        path: /etc/apt/keyrings/
        state: directory
        mode: '0755'

    - name: Download Grafana GPG key
      command: wget -q -O - https://apt.grafana.com/gpg.key
      register: grafana_gpg_key

    - name: Save Grafana GPG key
      copy:
        content: "{{ grafana_gpg_key.stdout }}"
        dest: /etc/apt/keyrings/grafana.gpg
        mode: '0644'

    - name: Update APT package list
      apt:
        update_cache: yes  
    
    - name: Add Grafana APT repository
      blockinfile:
        path: /etc/apt/sources.list.d/grafana.list
        block: |
          deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main
        create: yes
        insertbefore: EOF


    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install Grafana dependencies
      apt:
        name:
          - adduser
          - libfontconfig1
          - musl
        state: present

    - name: Download Grafana enterprise package
      get_url:
        url: "https://dl.grafana.com/enterprise/release/grafana-enterprise_{{ grafana_version }}_amd64.deb"
        dest: "{{ download_dir }}/grafana-enterprise_{{ grafana_version }}_amd64.deb"

    - name: Install Grafana enterprise package
      apt:
        deb: "{{ download_dir }}/grafana-enterprise_{{ grafana_version }}_amd64.deb"

    - name: Add Grafana bin directory to PATH
      lineinfile:
        path: /etc/profile
        line: "export PATH=/usr/share/grafana/bin:$PATH"
        state: present

    - name: Create Grafana provisioning directory
      file:
        path: /etc/grafana/provisioning/datasources
        state: directory
        mode: '0755'

    - name: Create Prometheus datasource configuration file
      copy:
        dest: /etc/grafana/provisioning/datasources/prometheus.yaml
        content: |
          api.version: 1
          datasources:
            - name: Prometheus
              type: prometheus
              url: "{{ prometheus_url }}"
        mode: '0644'

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Start Grafana server
      service:
        name: grafana-server
        state: started
        enabled: yes
