---
- name: Install node_exporter for Web and DB servers
  hosts: 
    - web_servers 
    - db_servers
  become: true
  tasks:

    - name: Install node_exporter package
      package:
        name: node_exporter
        state: present

    - name: Ensure node_exporter service is started and enabled
      systemd:
        name: node_exporter
        state: started
        enabled: yes